name: MadIntrovertSkills
favicon: null
layout_spectrum: 0.49732
typography_spectrum: 0.1153
title: The Pondering Man/Woman Revolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaca48'
    - '#7be9e0'
    - '#fdf0e3'
    - '#2344f6'
    - '#1e1e1e'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
