name: MadIntrovertSkills
favicon: null
layout_spectrum: 0.09632875164970756
typography_spectrum: 0.7902518881019205
title: The Pondering Revolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.08514495310373604
  lightness: 0.364511261228472
  saturation: 0.9936479234602302
  rhythmicContrast: 0.3769205375574529
purpose: []
