name: MadIntrovertSkills
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1195
title: The Pondering Revolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#75ea3e'
    - '#e6f1fe'
    - '#1e1e1e'
    - '#2b521e'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
